sudo: required
language: elixir
elixir:
  - 1.7.3
before_install:
  - curl -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.0.deb && sudo dpkg -i --force-confnew elasticsearch-6.4.0.deb
  - sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu
  - sudo service elasticsearch start
  - wget --retry-connrefused --no-check-certificate -T 60 localhost:9200 -O /dev/null
script: "mix test"
