sudo: required
language: elixir
elixir:
  - 1.4.1
before_install:
  - curl -L -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.3.1.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.1.deb
  - sudo /usr/share/elasticsearch/bin/plugin install analysis-icu
  - sudo service elasticsearch start
  - wget --retry-connrefused --no-check-certificate -T 60 localhost:9200 -O /dev/null
script: "mix test"
